AllCops:
  Exclude:
    - '**/vendor/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Gemfile'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
